@startuml Scheme
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container_Ext(esp32, "ESP32 MCU", "Modbus TCP Master, MQTT producer", "Опрашивает slave устройства по Modbus TCP и отправляет данные в соответствующие топики MQTT")
System_Ext(mqtt, "MQTT брокер")
Container(alarm_detecter, "Alarm Detecter", "MQTT, HTTP", "Слушает очередь MQTT и отправляет факт отклонения данных от нормы на сервер")
System_Ext(alarm_server, "Alarm Server", "Принимает и фиксирует отклонения данных")

Rel_R(esp32, mqtt, "Данные", "MQTT")
Rel(mqtt, alarm_detecter, "Данные", "MQTT")
Rel_L(alarm_detecter, alarm_server, "Отклоняющиеся данные", "HTTP")
@enduml